import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "React music player",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="font-sans text-black dark:text-white dark:bg-black h-full">
        {children}
      </body>
    </html>
  );
}
